=== irvingmike/2015_Summer_Classes/AWD_368_Online/xngr-editor/projects/Schema Viewer/dtd/contacts.dtd
<!ELEMENT Contacts (Person)+>

<!ELEMENT Person (Firstname,Lastname,Birthday?,Company,Position,Email+,
                  Address*)>
<!ELEMENT Firstname (#PCDATA)>

<!ELEMENT Lastname (#PCDATA)>

<!ELEMENT Birthday (#PCDATA)>

<!ELEMENT Position (#PCDATA)>

<!ELEMENT Email (#PCDATA)>

<!ELEMENT Address (Company?,Street,City,(Postcode|ZIP),Country)>
<!ATTLIST Address
  type NMTOKEN #IMPLIED>

<!ELEMENT Street (#PCDATA)>

<!ELEMENT City (#PCDATA)>

<!ELEMENT Postcode (#PCDATA)>

<!ELEMENT ZIP (#PCDATA)>

<!ELEMENT Country (#PCDATA)>

<!ELEMENT Company (#PCDATA)>

=== irvingmike/2015_Summer_Classes/AWD_368_Online/xngr-editor/projects/Schema Viewer/contacts.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Contacts SYSTEM "./dtd/contacts.dtd">

<Contacts>
	<Person>
		<Firstname>John</Firstname>
		<Lastname>Smith</Lastname>
		<Birthday>1965-03-29T13:20:00-05:00</Birthday>
		<Company>IBM</Company>
		<Position>CEO</Position>
		<Email>jsmith@ibm.com</Email>
		<Email>jsmith@yahoo.com</Email>
		<Address type="home">
			<Company/>
			<Street>23 Main St</Street>
			<City>Dublin</City>
			<Postcode>4</Postcode>
			<Country/>
		</Address>
		<Address type="work">
			<Street>1234 High St</Street>
			<City>London</City>
			<ZIP>1234</ZIP>
			<Country>Ireland</Country>
		</Address>
	</Person>
	<Person>
		<Firstname>Tom</Firstname>
		<Lastname>Dunne</Lastname>
		<Company>Today FM</Company>
    <Position/>
		<Email>tom.dunn@todayfm.com</Email>
	</Person>
</Contacts>
