=== irvingmike/2015_Summer_Classes/AWD_368_Online/Projects/Project3/project3schema.xsd
<?xml version="1.0"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="exchanges">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="exchange" type="exchangeType" minOccurs="4" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="exchangeType">
        <xsd:sequence>
            <xsd:element name="name" type="nameType" />
            <xsd:element name="address" type="addressType" />
            <xsd:element name="telephone" type="phoneType" />
            <xsd:element name="emailAddress" type="xsd:string" />
            <xsd:element name="applicationDate" type="dateType" />
            <xsd:element name="availableDate" type="dateType" />
            <xsd:element name="birthCountry" type="alphaType" />
            <xsd:element name="dateOfBirth" type="dateType" minOccurs="0" maxOccurs="1" />
            <xsd:element name="age" minOccurs="0" maxOccurs="1">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:int">
                        <xsd:minInclusive value="13" />
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="gender" type="genderType" />
            <xsd:element name="schoolName" type="alphaType" />
            <xsd:element name="schoolAddress" type="addressType" />
            <xsd:element name="yearInSchool" type="xsd:string" minOccurs="0" maxOccurs="1" />
            <xsd:element name="motherName" type="nameType" minOccurs="0" maxOccurs="1" />
            <xsd:element name="fatherName" type="nameType" minOccurs="0" maxOccurs="1" />
            <xsd:element name="emergencyTelephone" type="phoneType" />
            <xsd:element name="feePaid" type="feeType" />
            <xsd:element name="essay">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:maxLength value="1000" />
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="spokenLanguages" type="languagesType" />
            <xsd:element name="countryChoices" type="countryChoicesType" />
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:ID" use="required" />
        <xsd:attribute name="exchangeType" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern value="[S|T]" />
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="nameType">
        <xsd:all>
            <xsd:element name="firstName" type="alphaType" />
            <xsd:element name="middleInitial" type="initialType" />
            <xsd:element name="lastName" type="alphaType" />
        </xsd:all>
    </xsd:complexType>

    <xsd:simpleType name="alphaType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[\s\-'A-Za-z]{1,}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="initialType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[A-Z]?" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="addressType">
        <xsd:sequence>
            <xsd:element name="street" type="xsd:string" />
            <xsd:element name="apartment" type="xsd:string" minOccurs="0" maxOccurs="1" />
            <xsd:element name="city" type="xsd:string" />
            <xsd:choice>
                <xsd:element name="state" type="alphaType" />
                <xsd:element name="province" type="alphaType" />
            </xsd:choice>
            <xsd:choice>
                <xsd:element name="zipCode" type="zipType" />
                <xsd:element name="postalCode">
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:maxLength value="12" />
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:element>
            </xsd:choice>
            <xsd:element name="country" type="alphaType" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="zipType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="\d{5}(-\d{4})?" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="phoneType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="\(\d{3}\)\s\d{3}-\d{4}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="dateType">
        <xsd:sequence>
            <xsd:element name="month">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:unsignedByte">
                        <xsd:minInclusive value="1"/>
                        <xsd:maxInclusive value="12"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="day">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:unsignedByte">
                        <xsd:minInclusive value="1"/>
                        <xsd:maxInclusive value="31"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="year" type="xsd:gYear" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="genderType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[M|F]" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="feeType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:double">
                <xsd:attribute name="currency" use="required">
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:pattern value="USD|JPY|BRL|GBP|PAB" />
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:attribute>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="languagesType">
        <xsd:sequence>
            <xsd:element name="language" type="languageType" minOccurs="2" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="languageType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="fluency" use="required">
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:pattern value="[1-4]" />
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:attribute>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="countryChoicesType">
        <xsd:sequence>
            <xsd:element name="countryChoice" type="countryChoiceType" minOccurs="5" maxOccurs="5" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="countryChoiceType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="rank" use="required">
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:pattern value="[1-5]" />
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:attribute>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

</xsd:schema>

=== irvingmike/2015_Summer_Classes/AWD_368_Online/Projects/Project3/project3schema.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>

<!--
  Name: Aaron Anderson
  Assignment: Lab Project 3 Schema (Based on Project 2.1)
  Date: 08/6/2015
-->

<exchanges  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="project3schema.xsd">

	<exchange id="I00001" exchangeType="S">
		<name>
			<lastName>Anderson</lastName>
			<firstName>Aaron</firstName>
			<middleInitial>R</middleInitial>
		</name>
		<address>
			<street>1701 Wright Street</street>
			<apartment></apartment>
			<city>Madison</city>
			<state>WI</state>
			<zipCode>53704</zipCode>
			<country>United States</country>
		</address>
		<telephone>(608) 555-1234</telephone>
		<emailAddress>studentemail@madisoncollege.edu</emailAddress>
		<applicationDate>
			<month>3</month>
			<day>23</day>
			<year>2015</year>
		</applicationDate>
		<availableDate>
			<month>3</month>
			<day>25</day>
			<year>2015</year>
		</availableDate>
		<birthCountry>United States</birthCountry>
		<dateOfBirth>
			<month>1</month>
			<day>22</day>
			<year>1997</year>
		</dateOfBirth>
		<age>18</age>
		<gender>M</gender>
		<schoolName>Madison Area High School</schoolName>
		<schoolAddress>
			<street>123 School Street</street>
			<city>Madison</city>
			<state>WI</state>
			<zipCode>53717</zipCode>
			<country>USA</country>
		</schoolAddress>
		<yearInSchool>Senior</yearInSchool>
		<motherName>
			<lastName>StudentParent</lastName>
			<firstName>Mom</firstName>
			<middleInitial>H</middleInitial>
		</motherName>
		<fatherName>
			<lastName>StudentParent</lastName>
			<firstName>Dad</firstName>
			<middleInitial>K</middleInitial>
		</fatherName>
		<emergencyTelephone>(608) 123-4567</emergencyTelephone>
		<feePaid currency="USD">500.00</feePaid>
		<essay>
			<![CDATA[Sample of exchange essay for me to apply.  Why do I want to go?]]>
		</essay>
		<spokenLanguages>
			<language fluency="3">German</language>
			<language fluency="3">English</language>
			<language fluency="1">Spanish</language>
		</spokenLanguages>
		<countryChoices>
			<countryChoice rank="1">Germany</countryChoice>
			<countryChoice rank="3">Brazil</countryChoice>
			<countryChoice rank="5">Mexico</countryChoice>
			<countryChoice rank="2">France</countryChoice>
			<countryChoice rank="4">England</countryChoice>
		</countryChoices>
	</exchange>

	<exchange id="I00002" exchangeType="S">
		<name>
			<lastName>Smith-William</lastName>
			<firstName>Julian</firstName>
			<middleInitial>J</middleInitial>
		</name>
		<address>
			<street>123 Some Street</street>
			<apartment></apartment>
			<city>Portland</city>
			<state>OR</state>
			<zipCode>12345</zipCode>
			<country>United States</country>
		</address>
		<telephone>(123) 123-4567</telephone>
		<emailAddress>smith-william@madisoncollege.edu</emailAddress>
		<applicationDate>
			<month>1</month>
			<day>14</day>
			<year>2015</year>
		</applicationDate>
		<availableDate>
			<month>2</month>
			<day>13</day>
			<year>2015</year>
		</availableDate>
		<birthCountry>United States</birthCountry>
		<dateOfBirth>
			<month>4</month>
			<day>5</day>
			<year>1998</year>
		</dateOfBirth>
		<age>16</age>
		<gender>M</gender>
		<schoolName>Westview High School</schoolName>
		<schoolAddress>
			<street>44566 Westview Road</street>
			<city>Portland</city>
			<state>Oregon</state>
			<zipCode>12345</zipCode>
			<country>United States</country>
		</schoolAddress>
		<yearInSchool>Junior</yearInSchool>
		<motherName>
			<lastName>Smith</lastName>
			<firstName>Peggy</firstName>
			<middleInitial>H</middleInitial>
		</motherName>
		<fatherName>
			<lastName>Williams</lastName>
			<firstName>Ralph</firstName>
			<middleInitial>Y</middleInitial>
		</fatherName>
		<emergencyTelephone>(608) 555-4456</emergencyTelephone>
		<feePaid currency="USD">50.00</feePaid>
		<essay>
			<![CDATA[I have worked all my life and would like to travel. In order for me to be considered to be a foreign exchange student, I would need a scholarship.]]>
		</essay>
		<spokenLanguages>
			<language fluency="2">Greek</language>
			<language fluency="4">English</language>
		</spokenLanguages>
		<countryChoices>
			<countryChoice rank="2">Finland</countryChoice>
			<countryChoice rank="5">Norway</countryChoice>
			<countryChoice rank="1">Brazil</countryChoice>
			<countryChoice rank="3">Japan</countryChoice>
			<countryChoice rank="4">Egypt</countryChoice>
		</countryChoices>
	</exchange>

	<exchange id="I00003" exchangeType="S">
		<name>
			<lastName>Morimoto</lastName>
			<firstName>Vivian</firstName>
			<middleInitial></middleInitial>
		</name>
		<address>
			<street>112 Japan Street</street>
			<city>Bunkyo-ku</city>
			<province>Tokyo</province>
			<postalCode>100-6805</postalCode>
			<country>Japan</country>
		</address>
		<telephone>(111) 222-3333</telephone>
		<emailAddress>vmorimoto@madisoncollege.edu</emailAddress>
		<applicationDate>
			<month>1</month>
			<day>6</day>
			<year>2015</year>
		</applicationDate>
		<availableDate>
			<month>2</month>
			<day>13</day>
			<year>2015</year>
		</availableDate>
		<birthCountry>Japan</birthCountry>
		<dateOfBirth>
			<month>9</month>
			<day>3</day>
			<year>1997</year>
		</dateOfBirth>
		<age>17</age>
		<gender>F</gender>
		<schoolName>Tokyo's Finest High School</schoolName>
		<schoolAddress>
			<street>1223 High School Street</street>
			<city>Bunkyo-ku</city>
			<province>Tokyo</province>
			<postalCode>100-6805</postalCode>
			<country>Japan</country>
		</schoolAddress>
		<yearInSchool>Junior</yearInSchool>
		<motherName>
			<lastName>Morimoto</lastName>
			<firstName>Tina</firstName>
			<middleInitial>K</middleInitial>
		</motherName>
		<fatherName>
			<lastName>Morimoto</lastName>
			<firstName>Katsumoto</firstName>
			<middleInitial>Q</middleInitial>
		</fatherName>
		<emergencyTelephone>(608) 555-2222</emergencyTelephone>
		<feePaid currency="JPY">1000.00</feePaid>
		<essay>
			<![CDATA[This would be a great opportunity for me to get out and see the world. I truly enjoy living in Japan, but I would also love to travel around the world and this opportunity would give me a chance to do so.  France would be a dream trip, but going to the United States would also be quite wonderful.  Those are my top two choices, but in the end--any opportunity to go to any country would be an absolute thrill!!]]>
		</essay>
		<spokenLanguages>
			<language fluency="3">Engish</language>
			<language fluency="4">Japanese</language>
			<language fluency="2">French</language>
		</spokenLanguages>
		<countryChoices>
			<countryChoice rank="2">United States</countryChoice>
			<countryChoice rank="4">Germany</countryChoice>
			<countryChoice rank="3">Canada</countryChoice>
			<countryChoice rank="5">Italy</countryChoice>
			<countryChoice rank="1">France</countryChoice>
		</countryChoices>
	</exchange>

	<exchange id="I000004" exchangeType="T">
		<name>
			<lastName>Walden</lastName>
			<firstName>Mary-Jo</firstName>
			<middleInitial>U</middleInitial>
		</name>
		<address>
			<street>333 North Shore Blvd</street>
			<apartment>310</apartment>
			<city>Miami</city>
			<state>FL</state>
			<zipCode>32408</zipCode>
			<country>United States</country>
		</address>
		<telephone>(555) 222-4456</telephone>
		<emailAddress>teacher@madisoncollege.edu</emailAddress>
		<applicationDate>
			<month>5</month>
			<day>22</day>
			<year>2014</year>
		</applicationDate>
		<availableDate>
			<month>6</month>
			<day>1</day>
			<year>2015</year>
		</availableDate>
		<birthCountry>Canada</birthCountry>
		<gender>F</gender>
		<schoolName>Simple High School</schoolName>
		<schoolAddress>
			<street>1223 Some Nice Street</street>
			<city>Miami</city>
			<state>FL</state>
			<zipCode>32417</zipCode>
			<country>United States</country>
		</schoolAddress>
		<emergencyTelephone>(333) 435-3423</emergencyTelephone>
		<feePaid currency="USD">200.00</feePaid>
		<essay>
			<![CDATA[I am coming to bring my knowledge and experience to others, but more so to learn from others and become a better person.]]>
		</essay>
		<spokenLanguages>
			<language fluency="2">German</language>
			<language fluency="4">English</language>
			<language fluency="3">Japanese</language>
		</spokenLanguages>
		<countryChoices>
			<countryChoice rank="4">Germany</countryChoice>
			<countryChoice rank="1">Japan</countryChoice>
			<countryChoice rank="3">Brazil</countryChoice>
			<countryChoice rank="5">Germany</countryChoice>
			<countryChoice rank="2">France</countryChoice>
		</countryChoices>
	</exchange>
</exchanges>
